version: '3'

services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
